dataset:
  audio_loader:
    is_mono: true
    is_normalize: false  # min-max normalization
    crop_to_length_in_sec: 
      train: 20.0
      valid: 20.0
      test: 20.0

  dataset: MEDLEYDB
  input_type: audio # [audio, feature]
  input_dir: data/medleydb/V1/
  metadata_dir: data/medleydb/data/Annotations/Melody/Melody2

model:    
  feature_extractor:
    pretrain:
      !include benchmark/models/musichubert_hf/MERT-v0-public.yaml
    force_half: false
    reduction: none # [mean, max, min, none]

  downstream_structure:
    components:
      - name: feature_selector
        layer: all # [all, 0, 1, 2, ..., $n_tranformer_layer]
        # weighted sum is only effective when layer is set to all
        normalized_weight_sum: true

      - name: mlp
        hidden_layer_sizes: [512]
        dropout_p: 0.2
        num_outputs: 360

  voicing_threshold: 0.15
  post_processing: nearest_interpolation
  focal_loss: false


trainer: 
  # pytorch lightning trainer args
  auto_lr_find: false
  accelerator: gpu
  devices: -1
  strategy: ddp_find_unused_parameters_false # [null, ddp]
  precision: 16
  accumulate_grad_batches: 8
  fast_dev_run: false
  log_every_n_steps: 5
  max_epochs: 100 

  # custom args
  seed: 1234
  eval_only: false
  paradigm: probe # [probe, finetune]


dataloader:
  num_workers: 20
  batch_size:
    train: 8
    valid: 1
    test: 1


optimizer:
  name: torch.optim.AdamW
  l2_weight_decay: 0.1
  lr: 5e-3


scheduler:
  lr_scheduler_patience: 6
  earlystop_patience: 20


loss:
  loss_weight: null


logger:
  wandb_off: false # turn off wandb
  wandb_proj_name: Eval_MEDELYDB_probing
  wandb_run_name: null
  wandb_dir: /import/c4dm-05/nw003/benchmark
  wandb_sweep: false
  monitor: valid_oas


checkpoint:
  save_best_to: '/import/c4dm-05/nw003/benchmark/checkpoints/mlp.ckpt'
  eval_ckpt_path: null


hp_search:
  enable: false
  framework: ray
  technique: grid_search # [grid_search, random_search, bayesian_optimization, hyperband, asha]
  search_list: 
    - name: lr
      space: [1e-2, 5e-3, 1e-3, 5e-4, 1e-4, 5e-5]

 
