_import:
  - !include benchmark/tasks/NSynth/NSynthI_base_config.yaml

dataset:
  pre_extract:
    accelerator: gpu
    audio_dir: data/NSynth/nsynth-data
    output_dir: data/NSynth/encodec_features/encodec_feature_default
    keep_folder_structure: true
    overwrite: true

    feature_extractor:
      pretrain:
        !include benchmark/models/encodec/encodec.yaml

  dataset: NSynthI
  input_type: feature # [audio, feature]
  input_dir: data/NSynth/encodec_features/encodec_feature_default
  metadata_dir: data/NSynth/nsynth-data

model:    
    downstream_structure:
      components:
        - name: feature_selector
          layer: 0 # not a transformer model, so layer is set to 0
        - name: mlp
          hidden_layer_sizes: [512]
          dropout_p: 0.2
          num_outputs: 11
  